import { CaseCategory, CaseStatus, PriorityLevel, LegalRule, UserRole } from '../types';

export const DUC_HOP_COMMUNE_INFO = {
  unitTitle: 'CÔNG AN XÃ ĐỨC HỢP',
  provinceTitle: 'CÔNG AN TỈNH HƯNG YÊN',
  systemName: 'HÒM THƯ TỐ GIÁC TỘI PHẠM SỐ',
  address: 'Thôn Nho Lâm, xã Đức Hợp, tỉnh Hưng Yên',
  hotlineDirect: '02213.815.999',
  emergencyHotlines: [
    { label: 'Trực ban Công an xã Đức Hợp', phone: '02213.815.999', note: '24/7 Tiếp nhận khẩn cấp' },
    { label: 'Cảnh sát phản ứng nhanh (Toàn quốc)', phone: '113', note: 'Trường hợp đe dọa tính mạng' },
    { label: 'Cứu hỏa & Cứu nạn cứu hộ', phone: '114', note: 'Cháy nổ, sạt lở' },
    { label: 'Cấp cứu y tế', phone: '115', note: 'Cấp cứu người bị thương' },
  ],
  notificationEmail: 'conganxaduchopdangbai@gmail.com',
  leadershipAndOfficers: [
    {
      fullName: 'Đoàn Ngọc Quang',
      rank: 'Thượng tá',
      position: 'Trưởng Công an xã',
      phone: '0983.892.222',
      badgeNumber: '343-001',
      username: 'Quang343001',
      role: 'LEADERSHIP' as UserRole,
      department: 'Ban Chỉ huy Công an xã',
      assignedVillages: ['Nho Lâm', 'Đức An', 'Đức Trung'],
    },
    {
      fullName: 'Phạm Văn Hài',
      rank: 'Thiếu tá',
      position: 'Phó trưởng Công an xã',
      charge: 'Phụ trách Phòng chống tội phạm',
      phone: '0986.106.548',
      badgeNumber: '343-002',
      username: 'Hai343002',
      role: 'LEADERSHIP' as UserRole,
      department: 'Tổ Phòng chống tội phạm & tệ nạn',
      assignedVillages: ['Phú Ninh', 'Hạnh Lâm', 'Vân Nghệ'],
    },
    {
      fullName: 'Đặng Hồng Ngọc',
      rank: 'Trung tá',
      position: 'Phó trưởng Công an xã',
      charge: 'Phụ trách Tổng hợp',
      phone: '0944.061.666',
      badgeNumber: '343-003',
      username: 'Ngoc343003',
      role: 'LEADERSHIP' as UserRole,
      department: 'Tổ Tổng hợp & Tiếp nhận',
      assignedVillages: ['Trung Hòa', 'Phú Cường'],
    },
    {
      fullName: 'Vũ Văn Thu',
      rank: 'Trung tá',
      position: 'Phó trưởng Công an xã',
      charge: 'Phụ trách Cảnh sát trật tự',
      phone: '0988.178.118',
      badgeNumber: '343-004',
      username: 'Thu343004',
      role: 'LEADERSHIP' as UserRole,
      department: 'Tổ Cảnh sát trật tự & Giao thông',
      assignedVillages: ['Quảng Lạc', 'Bắc Nam Phú'],
    },
    {
      fullName: 'Nguyễn Văn Doanh',
      rank: 'Trung tá',
      position: 'Cán bộ',
      charge: 'Phụ trách Cảnh sát khu vực',
      phone: '0987.668.867',
      badgeNumber: '343-005',
      username: 'Doanh343005',
      role: 'PROCESSING_OFFICER' as UserRole,
      department: 'Tổ Cảnh sát khu vực',
      assignedVillages: ['Tây Thịnh', 'Đức An', 'Đức Trung', 'Phú Ninh'],
    },
    {
      fullName: 'Phạm Văn Ngoạn',
      rank: 'Thiếu tá',
      position: 'Cán bộ',
      charge: 'Phụ trách An ninh',
      phone: '0987.827.336',
      badgeNumber: '343-006',
      username: 'Ngoan343006',
      role: 'PROCESSING_OFFICER' as UserRole,
      department: 'Tổ An ninh & Bảo vệ mục tiêu',
      assignedVillages: ['Nho Lâm', 'Hạnh Lâm', 'Vân Nghệ', 'Trung Hòa', 'Phú Cường', 'Quảng Lạc', 'Bắc Nam Phú', 'Tây Thịnh'],
    },
  ],
};

export const DUC_HOP_VILLAGES: string[] = [
  'Đức An',
  'Đức Trung',
  'Phú Ninh',
  'Nho Lâm',
  'Hạnh Lâm',
  'Vân Nghệ',
  'Trung Hòa',
  'Phú Cường',
  'Quảng Lạc',
  'Bắc Nam Phú',
  'Tây Thịnh',
];

export const CATEGORY_DETAILS: Record<
  CaseCategory,
  { label: string; description: string; badgeColor: string; icon: string }
> = {
  CRIME_REPORT: {
    label: 'Tố giác tội phạm',
    description: 'Hành vi có dấu hiệu tội phạm hình sự (trộm cắp, cướp giật, lừa đảo, cố ý gây thương tích...)',
    badgeColor: 'bg-red-100 text-red-800 border-red-200',
    icon: 'ShieldAlert',
  },
  CRIME_INFO: {
    label: 'Tin báo về tội phạm',
    description: 'Thông tin phát hiện nghi vấn chuẩn bị phạm tội, tụ điểm khả nghi hoặc đối tượng truy nã',
    badgeColor: 'bg-amber-100 text-amber-800 border-amber-200',
    icon: 'BellRing',
  },
  SECURITY_ORDER: {
    label: 'Phản ánh ANTT',
    description: 'Gây mất trật tự công cộng, tiếng ồn đêm khuya, lấn chiếm hành lang an toàn, tụ tập đông người',
    badgeColor: 'bg-blue-100 text-blue-800 border-blue-200',
    icon: 'Users',
  },
  LAW_VIOLATION: {
    label: 'Phản ánh vi phạm pháp luật',
    description: 'Vi phạm trật tự an toàn giao thông, vi phạm quy định cư trú, kinh doanh không phép...',
    badgeColor: 'bg-purple-100 text-purple-800 border-purple-200',
    icon: 'FileWarning',
  },
  SOCIAL_EVIL: {
    label: 'Phản ánh tệ nạn xã hội',
    description: 'Đánh bạc, số đề, sử dụng hoặc mua bán ma túy, mại dâm, mê tín dị đoan...',
    badgeColor: 'bg-rose-100 text-rose-800 border-rose-200',
    icon: 'Flame',
  },
  OTHER_INFO: {
    label: 'Thông tin khác',
    description: 'Vấn đề liên quan cần Công an xã xác minh, tư vấn giải quyết hoặc hỗ trợ người dân',
    badgeColor: 'bg-slate-100 text-slate-800 border-slate-200',
    icon: 'HelpCircle',
  },
};

export const PRIORITY_DETAILS: Record<
  PriorityLevel,
  { label: string; badgeColor: string; badgeBg: string; textClass: string; dotColor: string }
> = {
  NORMAL: {
    label: 'Bình thường',
    badgeColor: 'bg-emerald-50 text-emerald-700 border-emerald-200',
    badgeBg: 'bg-emerald-500',
    textClass: 'text-emerald-700',
    dotColor: '#10b981',
  },
  URGENT: {
    label: 'Khẩn cấp',
    badgeColor: 'bg-amber-50 text-amber-700 border-amber-200',
    badgeBg: 'bg-amber-500',
    textClass: 'text-amber-700',
    dotColor: '#f59e0b',
  },
  VERY_URGENT: {
    label: 'Rất khẩn cấp',
    badgeColor: 'bg-red-50 text-red-700 border-red-200 animate-pulse',
    badgeBg: 'bg-red-600',
    textClass: 'text-red-700',
    dotColor: '#dc2626',
  },
};

export const STATUS_DETAILS: Record<
  CaseStatus,
  {
    label: string;
    publicLabel: string;
    description: string;
    stepIndex: number;
    color: string;
    badgeClass: string;
    badgeColor?: string;
  }
> = {
  NEW: {
    label: 'Mới gửi',
    publicLabel: 'Đã tiếp nhận',
    description: 'Hồ sơ đã được gửi lên hệ thống và lưu trữ vào sổ tiếp nhận.',
    stepIndex: 1,
    color: 'slate',
    badgeClass: 'bg-slate-100 text-slate-700 border-slate-200',
    badgeColor: 'bg-slate-100 text-slate-700 border-slate-200',
  },
  RECEIVED: {
    label: 'Đã tiếp nhận',
    publicLabel: 'Đã tiếp nhận',
    description: 'Cán bộ trực ban đã xác nhận tiếp nhận thông tin phản ánh.',
    stepIndex: 1,
    color: 'blue',
    badgeClass: 'bg-blue-100 text-blue-800 border-blue-200',
    badgeColor: 'bg-blue-100 text-blue-800 border-blue-200',
  },
  CLASSIFIED: {
    label: 'Đã phân loại',
    publicLabel: 'Đang phân loại',
    description: 'Đã phân loại tính chất vụ việc và chuyển Lãnh đạo phê duyệt.',
    stepIndex: 2,
    color: 'indigo',
    badgeClass: 'bg-indigo-100 text-indigo-800 border-indigo-200',
    badgeColor: 'bg-indigo-100 text-indigo-800 border-indigo-200',
  },
  ASSIGNED: {
    label: 'Đã phân công',
    publicLabel: 'Đã chuyển cán bộ xử lý',
    description: 'Lãnh đạo Công an xã đã giao cán bộ chuyên trách tiến hành giải quyết.',
    stepIndex: 3,
    color: 'purple',
    badgeClass: 'bg-purple-100 text-purple-800 border-purple-200',
    badgeColor: 'bg-purple-100 text-purple-800 border-purple-200',
  },
  PROCESSING: {
    label: 'Đang xử lý',
    publicLabel: 'Đang xử lý',
    description: 'Cán bộ đang triển khai các biện pháp nghiệp vụ theo quy trình.',
    stepIndex: 4,
    color: 'amber',
    badgeClass: 'bg-amber-100 text-amber-800 border-amber-200',
    badgeColor: 'bg-amber-100 text-amber-800 border-amber-200',
  },
  VERIFYING: {
    label: 'Đang xác minh',
    publicLabel: 'Đang xác minh thực địa',
    description: 'Công an xã đang tiến hành kiểm tra, xác minh thực địa tại hiện trường.',
    stepIndex: 4,
    color: 'orange',
    badgeClass: 'bg-orange-100 text-orange-800 border-orange-200',
    badgeColor: 'bg-orange-100 text-orange-800 border-orange-200',
  },
  WAITING_INFO: {
    label: 'Chờ bổ sung tin',
    publicLabel: 'Cần bổ sung thông tin',
    description: 'Cần người dân cung cấp thêm hình ảnh, chi tiết hoặc nhân chứng.',
    stepIndex: 4,
    color: 'yellow',
    badgeClass: 'bg-yellow-100 text-yellow-800 border-yellow-200',
    badgeColor: 'bg-yellow-100 text-yellow-800 border-yellow-200',
  },
  TRANSFERRED: {
    label: 'Đang phối hợp/Điều chuyển',
    publicLabel: 'Đang phối hợp xử lý',
    description: 'Đang phối hợp cùng các đơn vị nghiệp vụ hoặc điều chuyển theo thẩm quyền.',
    stepIndex: 5,
    color: 'cyan',
    badgeClass: 'bg-cyan-100 text-cyan-800 border-cyan-200',
    badgeColor: 'bg-cyan-100 text-cyan-800 border-cyan-200',
  },
  RESOLVED: {
    label: 'Đã xử lý xong',
    publicLabel: 'Đã xử lý xong',
    description: 'Vụ việc đã được xử lý xong, có kết luận và biện pháp giải quyết.',
    stepIndex: 6,
    color: 'emerald',
    badgeClass: 'bg-emerald-100 text-emerald-800 border-emerald-200',
    badgeColor: 'bg-emerald-100 text-emerald-800 border-emerald-200',
  },
  ARCHIVED: {
    label: 'Lưu trữ hồ sơ',
    publicLabel: 'Lưu trữ hồ sơ',
    description: 'Hồ sơ đã hoàn tất và được chuyển vào kho lưu trữ số an ninh.',
    stepIndex: 7,
    color: 'slate',
    badgeClass: 'bg-slate-100 text-slate-800 border-slate-200',
    badgeColor: 'bg-slate-100 text-slate-800 border-slate-200',
  },
  CLOSED: {
    label: 'Đã kết thúc hồ sơ',
    publicLabel: 'Kết thúc',
    description: 'Lãnh đạo đã phê duyệt kết quả và lưu trữ hồ sơ theo quy định.',
    stepIndex: 7,
    color: 'teal',
    badgeClass: 'bg-teal-100 text-teal-800 border-teal-200',
    badgeColor: 'bg-teal-100 text-teal-800 border-teal-200',
  },
  OUT_OF_SCOPE: {
    label: 'Không thuộc thẩm quyền',
    publicLabel: 'Không thuộc thẩm quyền',
    description: 'Nội dung không thuộc thẩm quyền giải quyết của Công an xã (đã hướng dẫn chuyển đơn vị chức năng).',
    stepIndex: 7,
    color: 'rose',
    badgeClass: 'bg-rose-100 text-rose-800 border-rose-200',
    badgeColor: 'bg-rose-100 text-rose-800 border-rose-200',
  },
  REJECTED: {
    label: 'Từ chối tiếp nhận',
    publicLabel: 'Không đủ điều kiện tiếp nhận',
    description: 'Thông tin trùng lặp hoặc không có cơ sở xác minh.',
    stepIndex: 7,
    color: 'red',
    badgeClass: 'bg-red-100 text-red-800 border-red-200',
    badgeColor: 'bg-red-100 text-red-800 border-red-200',
  },
  CANCELLED: {
    label: 'Hủy hồ sơ',
    publicLabel: 'Hủy hồ sơ',
    description: 'Hồ sơ đã bị hủy do yêu cầu hoặc lý do pháp lý.',
    stepIndex: 7,
    color: 'gray',
    badgeClass: 'bg-gray-100 text-gray-800 border-gray-200',
    badgeColor: 'bg-gray-100 text-gray-800 border-gray-200',
  },
};

export const STATE_TRANSITIONS: Record<CaseStatus, CaseStatus[]> = {
  NEW: ['RECEIVED', 'OUT_OF_SCOPE', 'REJECTED'],
  RECEIVED: ['CLASSIFIED', 'OUT_OF_SCOPE'],
  CLASSIFIED: ['ASSIGNED', 'OUT_OF_SCOPE', 'REJECTED'],
  ASSIGNED: ['PROCESSING', 'TRANSFERRED', 'CLASSIFIED'],
  PROCESSING: ['VERIFYING', 'WAITING_INFO', 'RESOLVED', 'TRANSFERRED'],
  VERIFYING: ['PROCESSING', 'RESOLVED', 'WAITING_INFO'],
  WAITING_INFO: ['PROCESSING', 'CANCELLED', 'CLOSED'],
  TRANSFERRED: ['ASSIGNED', 'PROCESSING', 'RESOLVED'],
  RESOLVED: ['CLOSED', 'ARCHIVED', 'PROCESSING'],
  ARCHIVED: ['CLOSED'],
  OUT_OF_SCOPE: ['CLOSED'],
  REJECTED: ['CLOSED'],
  CANCELLED: ['CLOSED'],
  CLOSED: [],
};

export const DEFAULT_LEGAL_RULES: LegalRule[] = [
  {
    ruleId: 'LR-001',
    category: 'CRIME_REPORT',
    priority: 'VERY_URGENT',
    deadlineDays: 1, // 24h
    requiredActions: 'Cử ngay lực lượng xuống bảo vệ hiện trường, lấy lời khai ban đầu và báo cáo Trưởng Công an xã',
    description: 'Tố giác tội phạm đặc biệt khẩn cấp',
    active: true,
  },
  {
    ruleId: 'LR-002',
    category: 'CRIME_REPORT',
    priority: 'URGENT',
    deadlineDays: 3,
    requiredActions: 'Tiến hành xác minh nhân chứng, thu thập vật chứng và phân công điều tra viên thụ lý',
    description: 'Tố giác tội phạm khẩn cấp',
    active: true,
  },
  {
    ruleId: 'LR-003',
    category: 'CRIME_REPORT',
    priority: 'NORMAL',
    deadlineDays: 7,
    requiredActions: 'Phân loại tin báo, thụ lý và giải quyết theo Thông tư liên tịch về tiếp nhận tin báo tố giác',
    description: 'Tố giác tội phạm thông thường',
    active: true,
  },
  {
    ruleId: 'LR-004',
    category: 'CRIME_INFO',
    priority: 'NORMAL',
    deadlineDays: 5,
    requiredActions: 'Kiểm tra tàng thư nghiệp vụ, trinh sát địa bàn để thẩm tra tính xác thực',
    description: 'Tin báo tội phạm',
    active: true,
  },
  {
    ruleId: 'LR-005',
    category: 'SECURITY_ORDER',
    priority: 'URGENT',
    deadlineDays: 1,
    requiredActions: 'Tổ chức tuần tra, giải tán tụ tập, lập biên bản nhắc nhở hoặc xử lý vi phạm hành chính',
    description: 'Phản ánh an ninh trật tự khẩn',
    active: true,
  },
  {
    ruleId: 'LR-006',
    category: 'SECURITY_ORDER',
    priority: 'NORMAL',
    deadlineDays: 3,
    requiredActions: 'Cảnh sát khu vực mời các bên liên quan làm việc, hòa giải hoặc xử lý theo quy định',
    description: 'Phản ánh an ninh trật tự thông thường',
    active: true,
  },
  {
    ruleId: 'LR-007',
    category: 'SOCIAL_EVIL',
    priority: 'URGENT',
    deadlineDays: 2,
    requiredActions: 'Lập kế hoạch triệt phá, theo dõi đối tượng cầm đầu và báo cáo Công an tỉnh',
    description: 'Phản ánh tệ nạn cờ bạc, ma túy',
    active: true,
  },
  {
    ruleId: 'LR-008',
    category: 'LAW_VIOLATION',
    priority: 'NORMAL',
    deadlineDays: 5,
    requiredActions: 'Xác minh vi phạm, lập hồ sơ xử phạt vi phạm hành chính',
    description: 'Vi phạm quy định pháp luật',
    active: true,
  },
  {
    ruleId: 'LR-009',
    category: 'OTHER_INFO',
    priority: 'NORMAL',
    deadlineDays: 7,
    requiredActions: 'Giải đáp, hướng dẫn thủ tục hoặc giải quyết theo thẩm quyền',
    description: 'Thông tin khác',
    active: true,
  },
];
